SELECT 
CAB1.City AS address1_city,
CAB1.Country AS address1_country,
CAB1.Line1 AS address1_line1,
CAB1.Line2 AS address1_line2,
CAB1.StateOrProvince AS address1_stateorprovince,
CAB1.PostalCode AS address1_postalcode,
CAB2.City AS address2_city,
CAB2.Country AS address2_country,
CAB2.Line1 AS address2_line1,
CAB2.Line2 AS address2_line2,
CAB2.StateOrProvince AS address2_stateorprovince,
CAB2.PostalCode AS address2_postalcode,
CB.contactId,
CB.donotemail,
CB.donotphone,
CB.donotpostalmail,
CB.emailaddress1,
CB.emailaddress2,
SM9.Value AS familystatuscode,
CB.firstname,
CB.fiserv_accountcharacteristics,
CB.fiserv_accountsbusiness,
CB.fiserv_accountsbusinesschecking,
CB.fiserv_accountsdeposit,
CB.fiserv_accountsliquiddeposit,
CB.fiserv_accountsloanline,
CB.fiserv_accountspersonalchecking,
CB.fiserv_ageofprimaryaccountholder,
CB.fiserv_balanceiraaccounts,
CB.fiserv_balanceliquiddeposit,
CB.fiserv_balancemmaccounts,
CB.fiserv_balancemortgage,
CB.fiserv_balancepersonalcd,
CB.fiserv_balancepersonalchecking,
CB.fiserv_balancepersonalsavings,
CB.fiserv_branchnumber,
CB.fiserv_businessbankingrelationship,
SM1.Value AS fiserv_businesstypecode,
CB.fiserv_commercial_naics_code,
CB.fiserv_commercialrelationship,
CB.fiserv_customerid,
CB.fiserv_delinquent60days,
CB.fiserv_headofhousehold,
CB.fiserv_householdid,
CB.fiserv_investmentrelationship,
CB.fiserv_lastdeposittrandate,
SM8.Value AS fiserv_lineofbusinessindicator,
CB.fiserv_mortgages,
SM10.Value AS fiserv_occupationcode,
CB.fiserv_officername,
CB.fiserv_officernumber,
CB.fiserv_onlinebanking,
CB.fiserv_otherpartnerservices,
CB.fiserv_primaryssntinindicator,
CB.fiserv_privatebankingrelationship,
CB.fiserv_profit,
SM7.Value AS fiserv_profiletype,
SM2.Value AS fiserv_profitindicator,
SM3.Value AS fiserv_profittier,
CB.fiserv_relationshiptenure,
CB.fiserv_retail_hh_acct_cnt,
CB.fiserv_retail_hh_date_active,
CB.fiserv_retail_hh_deposit_bal,
CB.fiserv_retail_hh_loan_bal,
CB.fiserv_retail_how_pay_atm_dbt_card,
CB.fiserv_retail_hh_total_svc_cnt,
CB.fiserv_retail_prime_dob,
CB.fiserv_retail_prime_taxid,
CB.fiserv_retailrelationship,
SM4.Value AS fiserv_sensitivecustomer,
CB.fiserv_totalaccounts,
CB.fiserv_totalbalancebusinessloans,
CB.fiserv_totalbusinesschecking,
CB.fiserv_totalbusinesscommitments,
CB.fiserv_totalbusinessdepositaccounts,
CB.fiserv_totalbusinessdeposits,
CB.fiserv_totalbusinessloanaccounts,
CB.fiserv_totalloans,
CB.fiserv_totalpersdepositamt,
CB.fiserv_totalpersloanlineamt,
CB.fiserv_totalrelatdeposits,
CB.fiserv_treasuryservicesrelationship,
CB.fiserv_trustrelationship,
SM5.Value AS gendercode,
CB.lastname,
CB.middlename,
CB.mobilephone,
CB.modifiedon,
CB.ownerid,
CASE WHEN CB.OwnerIdType=8 THEN CAST('User' AS NVARCHAR(100)) WHEN CB.OwnerIdType=9 THEN CAST('Team' AS NVARCHAR(100)) ELSE NULL END AS OwnerIdType,
--CASE WHEN CB.OwnerIdType=8 THEN 'User' WHEN CB.OwnerIdType=9 THEN'Team' ELSE NULL END AS OwnerIdType,
TB.Name AS ownerteamname,
UB.FullName AS ownerusername,
CB.parentcustomerid,
CB.suffix,
CB.telephone1,
CB.telephone2,
CB.wtfiserv_billpayindicator,
CB.wtfiserv_branchname,
CB.wtfiserv_censustract,
CB.wtfiserv_charternumber,
CB.wtfiserv_creditcard,
CB.wtfiserv_debitcard,
CB.wtfiserv_donotcontactexceptionlist,
CB.wtfiserv_estatementsindicator,
CB.wtfiserv_fissecondaryofficername,
CB.wtfiserv_fissecondaryofficernumber,
CB.wtfiserv_identitytheftindicator,
CB.wtfiserv_juniorsavers,
SM6.Value AS wtfiserv_lowtomodorminority,
CB.wtfiserv_lastdateofcontact,
CB.wtfiserv_mobilebankingindicator,
CB.wtfiserv_mothersmaidenname,
CB.wtfiserv_nameofcharter,
CB.wtfiserv_officernamepreviousmonthend,
CB.wtfiserv_officernumberpreviousmonthend,
CB.wtfiserv_orgindividual,
CB.wtfiserv_password,
CB.wtfiserv_previousmonthsenddate,
CB.wtfiserv_privacyoptoutaffiliatesharing,
CB.wtfiserv_totalaccountspreviousmonthend,
CB.wtfiserv_totalcommitmentspreviousmonthend,
CB.wtfiserv_totalddadeposits,
CB.wtfiserv_totaldepositspreviousmonthend,
CB.wtfiserv_totalloanlineoutstandingprevmonthend,
CB.wtfiserv_totalnoncheckingdeposit,
CB.wtfiserv_totalnowdeposits,
CB.wtfiserv_wealthservicesrelationship
FROM Contactbase CB (NOLOCK)
JOIN CustomerAddressBase CAB1 (NOLOCK) on CB.ContactId=CAB1.ParentId and CAB1.AddressNumber=1
JOIN CustomerAddressBase CAB2 (NOLOCK) on CB.ContactId=CAB2.ParentId and CAB2.AddressNumber=2
FULL OUTER JOIN StringMap (NOLOCK) AS SM1 ON SM1.AttributeValue = CB.fiserv_businesstypecode AND SM1.ObjectTypeCode=2 AnD SM1.AttributeName = 'fiserv_businesstypecode'
FULL OUTER JOIN StringMap (NOLOCK) AS SM2 ON SM2.AttributeValue = CB.fiserv_profitindicator AND SM2.ObjectTypeCode=2 AnD SM2.AttributeName = 'fiserv_profitindicator'
FULL OUTER JOIN StringMap (NOLOCK) AS SM3 ON SM3.AttributeValue = CB.fiserv_profittier AND SM3.ObjectTypeCode=2 AnD SM3.AttributeName = 'fiserv_profittier'
FULL OUTER JOIN StringMap (NOLOCK) AS SM4 ON SM4.AttributeValue = CB.fiserv_sensitivecustomer AND SM4.ObjectTypeCode=2 AnD SM4.AttributeName = 'fiserv_sensitivecustomer'
FULL OUTER JOIN StringMap (NOLOCK) AS SM5 ON SM5.AttributeValue = CB.gendercode AND SM5.ObjectTypeCode=2 AnD SM5.AttributeName = 'gendercode'
FULL OUTER JOIN StringMap (NOLOCK) AS SM6 ON SM6.AttributeValue = CB.wtfiserv_lowtomodorminority AND SM6.ObjectTypeCode=2 AnD SM6.AttributeName = 'wtfiserv_lowtomodorminority'
FULL OUTER JOIN StringMap (NOLOCK) AS SM7 ON SM7.AttributeValue = CB.fiserv_profiletype AND SM7.ObjectTypeCode=2 AnD SM7.AttributeName = 'fiserv_profiletype'
FULL OUTER JOIN StringMap (NOLOCK) AS SM9 ON SM9.AttributeValue = CB.familystatuscode AND SM9.ObjectTypeCode=2 AnD SM9.AttributeName = 'familystatuscode'
FULL OUTER JOIN StringMap (NOLOCK) AS SM10 ON SM10.AttributeValue = CB.fiserv_occupationcode AND SM10.ObjectTypeCode=2 AnD SM10.AttributeName = 'fiserv_occupationcode'
FULL OUTER JOIN TeamBase (NOLOCK) TB on CB.OwnerId= TB.TeamId AND CB.OwnerIdType = 9
FULL OUTER JOIN SystemUserBase (NOLOCK) UB on CB.OwnerId= UB.SystemUserId AND CB.OwnerIdType = 8
FULL OUTER JOIN StringMap (NOLOCK) AS SM8 ON SM8.AttributeValue = UB.fiserv_lineofbusinessindicator AND SM8.ObjectTypeCode=8 AnD SM8.AttributeName = 'fiserv_lineofbusinessindicator'
WHERE CB.StateCode=0 AND CB.parentcustomerid IS NULL
AND CB.fiserv_profiletype in (1,2)
OR (CB.fiserv_profiletype =1 AND CB.modifiedon>'1/1/2018')
AND (CB.OwnerIdType=8 and UB.fiserv_lineofbusinessindicator in (3,28,15,14,19,16,12,10))
