SELECT 
contactid AS EnactCRMId,
ISNULL(address1_city,'') AS BillingCity,
ISNULL(address1_line1,'') AS BillingStreet,
ISNULL(address1_postalcode,'') AS BillingPostalCode,
ISNULL(address1_stateorprovince,'') AS BillingState,
ISNULL(address1_country,'') AS BillingCountry,
ISNULL(donotphone,'') AS PersonDoNotCall,
ISNULL(emailaddress1,'') AS PersonEmail,
ISNULL(firstname,'') AS FirstName,
ISNULL(fiserv_customerid,'') AS AccountNumber,
ISNULL(fiserv_retail_prime_dob,'') AS PersonBirthdate,
ISNULL(fiserv_retail_prime_taxid,'') AS FinServ__TaxId__pc,
ISNULL(RIGHT(fiserv_retail_prime_taxid,4),'') AS FinServ__LastFourDigitSSN__pc,
ISNULL(gendercode,'') AS FinServ__Gender__pc,
ISNULL(lastname,'') AS LastName,
ISNULL(middlename,'') AS MiddleName,
ISNULL(mobilephone,'') AS PersonMobilePhone,
ISNULL(telephone1,'') AS Phone,
ISNULL(telephone2,'') AS PersonHomePhone,
ISNULL(fiserv_profiletype,'') AS fiserv_profiletype,
CASE WHEN fiserv_profiletype='Customer' THEN CAST('Person Account Customer' AS NVARCHAR(100)) WHEN fiserv_profiletype='Prospect' THEN CAST('Person Account Prospect' AS NVARCHAR(100)) ELSE NULL END AS RecordType,
CASE WHEN fiserv_profiletype='Customer' THEN CAST('0123t000000mfbqAAA' AS NVARCHAR(18)) WHEN fiserv_profiletype='Prospect' THEN CAST('012f0000000S8GSAA0' AS NVARCHAR(18)) ELSE NULL END AS RecordTypeId
FROM Contact
